export const NOT_STARTED = '__notStarted__'

export const PREISSUANCE_OFFERED = 'offered'
export const PREISSUANCE_DISTRIBUTED = 'distributed'

export const ISSUANCE_LOCKED = 'locked'
export const ISSUANCE_RESERVED = 'reserved'
export const ISSUANCE_ISSUED = 'issued'
export const ISSUANCE_NOTARIZED = 'notarized'
export const ISSUANCE_FINALIZED = 'finalized'

export const KYC_ISSUER = 'issuer'
export const KYC_INVITED = 'invited'
export const KYC_SUBMITTED = 'kycSubmitted'
export const KYC_VALIDATED = 'validated'
export const KYC_REJECTED = 'rejected'

export const BASICS_EXECUTED = 'executed'

export const INITIALIZED = 'initialized'
export const PRE_INITIALIZED = 'preInitialized'
export const PRE_INITIALIZED_2 = 'preInitialized2'
export const DEPLOYED = 'deployed'
export const DEPLOYED_WITH_EXTENSION = 'deployedWithExtension'

export const SUBSCRIBED = 'subscribed'
export const PAID = 'paid'
export const PAYING = 'paying'
export const PAID_SETTLED = 'paidSettled'
export const UNPAID_SETTLED = 'unpaidSettled'
export const PAID_CANCELLED = 'paidCancelled'
export const UNPAID_CANCELLED = 'unpaidCancelled'
export const PAID_REJECTED = 'paidRejected'
export const UNPAID_REJECTED = 'unpaidRejected'

export const NAV_SUBMITTED = 'navSubmitted'
export const NAV_VALIDATED = 'navValidated'
export const NAV_REJECTED = 'navRejected'

export const PRE_CREATED = 'preCreated'
export const SUBMITTED = 'submitted'
export const PURCHASED = 'purchased'
export const APPROVED = 'approved'
export const ACCEPTED = 'accepted'
export const OUTSTANDING = 'outstanding'
// export const PAID = 'paid'
export const EXECUTED = 'executed'
export const CANCELLED = 'cancelled'
export const REJECTED = 'rejected'
export const NEGOTIATING = 'negotiating'
export const SCHEDULED = 'scheduled'
export const SETTLED = 'settled'
