FROM node:18

WORKDIR /usr/src/app

COPY . .

# Install dependencies using the Yarn cache from the previous build, if one exists.
RUN --mount=type=cache,target=/yarn YARN_CACHE_FOLDER=/yarn yarn install

# Build the Admin API and all its local dependencies.
RUN npx nx build admin-api

CMD [ "npx", "nx", "start:dev", "admin-api" ]
