version: '3.4'
services:
  entity-db:
    image: postgres
    networks:
      - codefi
    environment:
      - POSTGRES_DB=${DB_DATABASE_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5434:5432
  entity-api:
    env_file:
      - ../../../.env
      - .env
    environment:
      STORES_FILE: ${STORES_FILE-./config/stores.json}
    image: entity-api
    networks:
      - codefi
    ports:
      - 3008:3000
      - 9230:9229
    volumes:
      - ./src:/usr/src/app/platform/services/entity-api/src:delegated
      - ./integration:/usr/src/app/platform/services/entity-api/integration:delegated
    depends_on:
      - entity-db
    build:
      context: ../../../
      dockerfile: ./platform/services/entity-api/${DOCKERFILE-Dockerfile.dev}
    labels:
      local.filebeat: 'true'

volumes:
  db-data:
    driver: local

networks:
  codefi:
    external:
      name: local-dev-env-deps_codefi
