version: "3.4"
services:
  postgres:
    image: "postgres:11"
    hostname: postgres
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    env_file: ./.env
    ports:
      - "5432:5432"
