export interface ICountry {
  country: string;
  currency: string;
  code: string;
  length?: string;
  format?: string;
  currencyCode: string;
}

const countries: ICountry[] = [
  {
    currencyCode: 'USD',
    currency: 'US Dollar',
    country: 'United States of America',
    code: 'USA',
  },
  {
    country: 'United Kingdom',
    code: 'GB',
    format: 'GB2!n4!a6!n8!n',
    currencyCode: 'GBP',
    currency: 'Pound Sterling',
  },
  {
    currencyCode: 'CAD',
    currency: 'Canadian Dollar',
    country: 'Canada',
    code: 'CAN',
  },
  {
    currencyCode: 'AUD',
    currency: 'Australian Dollar',
    country: 'Australia',
    code: 'AUS',
  },
  {
    country: 'Albania',
    length: '28',
    code: 'AL',
    format: 'AL2!n8!n16!c',
    currency: 'Lek',
    currencyCode: 'ALL',
  },
  {
    country: 'Andorra',
    length: '24',
    code: 'AD',
    format: 'AD2!n4!n4!n12!c',
    currency: 'Euro',
    currencyCode: 'EUR',
  },
  {
    country: 'Austria',
    length: '20',
    code: 'AT',
    format: 'AT2!n5!n11!n',
    currency: 'Euro',
    currencyCode: 'EUR',
  },
  {
    country: 'Azerbaijan, Republic of',
    length: '28',
    code: 'AZ',
    format: 'AZ2!n4!a20!c',
    currencyCode: 'AZN',
    currency: 'Azerbaijan Manat',
  },
  {
    country: 'Bahrain',
    length: '22',
    code: 'BH',
    format: 'BH2!n4!a14!c',
    currency: 'Bahraini Dinar',
    currencyCode: 'BHD',
  },
  {
    country: 'Belgium',
    length: '16',
    code: 'BE',
    format: 'BE2!n3!n7!n2!n',
    currency: 'Euro',
    currencyCode: 'EUR',
  },
  {
    country: 'Bosnia and Herzegovina',
    length: '20',
    code: 'BA',
    format: 'BA2!n3!n3!n8!n2!n',
    currency: 'Convertible Mark',
    currencyCode: 'BAM',
  },
  {
    country: 'Brazil',
    length: '29',
    code: 'BR',
    format: 'BR2!n8!n5!n10!n1!a1!c',
    currency: 'Brazilian Real',
    currencyCode: 'BRL',
  },
  {
    country: 'Bulgaria',
    length: '22',
    code: 'BG',
    format: 'BG2!n4!a4!n2!n8!c',
    currency: 'Bulgarian Lev',
    currencyCode: 'BGN',
  },
  {
    country: 'Costa Rica',
    length: '21',
    code: 'CR',
    format: 'CR2!n3!n14!n',
    currency: 'Costa Rican Colon',
    currencyCode: 'CRC',
  },
  {
    country: 'Croatia',
    length: '21',
    code: 'HR',
    format: 'HR2!n7!n10!n',
    currency: 'Kuna',
    currencyCode: 'HRK',
  },
  {
    country: 'Cyprus',
    length: '28',
    code: 'CY',
    format: 'CY2!n3!n5!n16!c',
    currency: 'Euro',
    currencyCode: 'EUR',
  },
  {
    country: 'Czech Republic',
    length: '24',
    code: 'CZ',
    format: 'CZ2!n4!n6!n10!n',
    currencyCode: 'CZK',
    currency: 'Czech Koruna',
  },
  {
    country: 'Denmark',
    length: '18',
    code: 'DK',
    format: 'DK2!n4!n9!n1!n',
    currency: 'Danish Krone',
    currencyCode: 'DKK',
  },
  {
    country: 'Dominican Republic',
    length: '28',
    code: 'DO',
    format: 'DO2!n4!c20!n',
    currencyCode: 'DOP',
    currency: 'Dominican Peso',
  },
  {
    country: 'Estonia',
    length: '20',
    code: 'EE',
    format: 'EE2!n2!n2!n11!n1!n',
    currency: 'Euro',
    currencyCode: 'EUR',
  },
  {
    country: 'Faroe Islands',
    length: '18',
    code: 'FO',
    format: 'FO2!n4!n9!n1!n',
    currencyCode: 'DKK',
    currency: 'Danish Krone',
  },
  {
    country: 'Finland',
    length: '18',
    code: 'FI',
    format: 'FI2!n6!n7!n1!n',
    currency: 'Euro',
    currencyCode: 'EUR',
  },
  {
    country: 'France',
    length: '27',
    code: 'FR',
    format: 'FR2!n5!n5!n11!c2!n',
    currency: 'Euro',
    currencyCode: 'EUR',
  },
  {
    country: 'Georgia',
    length: '22',
    code: 'GE',
    format: 'GE2!n2!a16!n',
    currency: 'Lari',
    currencyCode: 'GEL',
  },
  {
    country: 'Germany',
    length: '22',
    code: 'DE',
    format: 'DE2!n8!n10!n',
    currency: 'Euro',
    currencyCode: 'EUR',
  },
  {
    country: 'Gibraltar',
    length: '23',
    code: 'GI',
    format: 'GI2!n4!a15!c',
    currency: 'Gibraltar Pound',
    currencyCode: 'GIP',
  },
  {
    country: 'Greece',
    length: '27',
    code: 'GR',
    format: 'GR2!n3!n4!n16!c',
    currency: 'Euro',
    currencyCode: 'EUR',
  },
  {
    country: 'Greenland',
    length: '18',
    code: 'GL',
    format: 'GL2!n4!n9!n1!n',
    currency: 'Danish Krone',
    currencyCode: 'DKK',
  },
  {
    country: 'Guatemala',
    length: '28',
    code: 'GT',
    format: 'GT2!n4!c20!c',
    currency: 'Quetzal',
    currencyCode: 'GTQ',
  },
  {
    country: 'Hungary',
    length: '28',
    code: 'HU',
    format: 'HU2!n3!n4!n1!n15!n1!n',
    currency: 'Forint',
    currencyCode: 'HUF',
  },
  {
    country: 'Iceland',
    length: '26',
    code: 'IS',
    format: 'IS2!n4!n2!n6!n10!n',
    currency: 'Iceland Krona',
    currencyCode: 'ISK',
  },
  {
    country: 'Ireland',
    length: '22',
    code: 'IE',
    format: 'IE2!n4!a6!n8!n',
    currency: 'Euro',
    currencyCode: 'EUR',
  },
  {
    country: 'Israel',
    length: '23',
    code: 'IL',
    format: 'IL2!n3!n3!n13!n',
    currency: 'New Israeli Sheqel',
    currencyCode: 'ILS',
  },
  {
    country: 'Italy',
    length: '27',
    code: 'IT',
    format: 'IT2!n1!a5!n5!n12!c',
    currency: 'Euro',
    currencyCode: 'EUR',
  },
  {
    country: 'Jordan',
    length: '30',
    code: 'JO',
    format: 'JO2!n4!a4!n18!c',
    currency: 'Jordanian Dinar',
    currencyCode: 'JOD',
  },
  {
    country: 'Kazakhstan',
    length: '20',
    code: 'KZ',
    format: 'KZ2!n3!n13!c',
    currency: 'Tenge',
    currencyCode: 'KZT',
  },
  {
    country: 'Kuwait',
    length: '30',
    code: 'KW',
    format: 'KW2!n4!a22!c',
    currency: 'Kuwaiti Dinar',
    currencyCode: 'KWD',
  },
  {
    country: 'Latvia',
    length: '21',
    code: 'LV',
    format: 'LV2!n4!a13!c',
    currency: 'Euro',
    currencyCode: 'EUR',
  },
  {
    country: 'Lebanon',
    length: '28',
    code: 'LB',
    format: 'LB2!n4!n20!c',
    currency: 'Lebanese Pound',
    currencyCode: 'LBP',
  },
  {
    country: 'Liechtenstein (Principality of)',
    length: '21',
    code: 'LI',
    format: 'LI2!n5!n12!c',
    currencyCode: 'CHF',
    currency: 'Swiss Franc',
  },
  {
    country: 'Lithuania',
    length: '20',
    code: 'LT',
    format: 'LT2!n5!n11!n',
    currency: 'Euro',
    currencyCode: 'EUR',
  },
  {
    country: 'Luxembourg',
    length: '20',
    code: 'LU',
    format: 'LU2!n3!n13!c',
    currency: 'Euro',
    currencyCode: 'EUR',
  },
  {
    country: 'North Macedonia',
    length: '19',
    code: 'MK',
    format: 'MK2!n3!n10!c2!n',
    currencyCode: 'MKD',
    currency: 'Denar',
  },
  {
    country: 'Malta',
    length: '31',
    code: 'MT',
    format: 'MT2!n4!a5!n18!c',
    currency: 'Euro',
    currencyCode: 'EUR',
  },
  {
    country: 'Mauritania',
    length: '27',
    code: 'MR',
    format: 'MR2!n5!n5!n11!n2!n',
    currency: 'Ouguiya',
    currencyCode: 'MRU',
  },
  {
    country: 'Mauritius',
    length: '30',
    code: 'MU',
    format: 'MU2!n4!a2!n2!n12!n3!n3!a',
    currency: 'Mauritius Rupee',
    currencyCode: 'MUR',
  },
  {
    country: 'Moldova',
    length: '24',
    code: 'MD',
    format: 'MD2!n2!c18!c',
    currencyCode: 'MDL',
    currency: 'Moldovan Leu',
  },
  {
    country: 'Monaco',
    length: '27',
    code: 'MC',
    format: 'MC2!n5!n5!n11!c2!n',
    currency: 'Euro',
    currencyCode: 'EUR',
  },
  {
    country: 'Montenegro',
    length: '22',
    code: 'ME',
    format: 'ME2!n3!n13!n2!n',
    currency: 'Euro',
    currencyCode: 'EUR',
  },
  {
    country: 'Netherlands',
    length: '18',
    code: 'NL',
    format: 'NL2!n4!a10!n',
    currency: 'Netherlands Guilder',
    currencyCode: 'NLG',
  },
  {
    country: 'Norway',
    length: '15',
    code: 'NO',
    format: 'NO2!n4!n6!n1!n',
    currency: 'Norwegian Krone',
    currencyCode: 'NOK',
  },
  {
    country: 'Pakistan',
    length: '24',
    code: 'PK',
    format: 'PK2!n4!a16!c',
    currency: 'Pakistan Rupee',
    currencyCode: 'PKR',
  },
  {
    country: 'Poland',
    length: '28',
    code: 'PL',
    format: 'PL2!n8!n16!n',
    currency: 'Zloty',
    currencyCode: 'PLN',
  },
  {
    country: 'Portugal',
    length: '25',
    code: 'PT',
    format: 'PT2!n4!n4!n11!n2!n',
    currency: 'Euro',
    currencyCode: 'EUR',
  },
  {
    country: 'Qatar',
    length: '29',
    code: 'QA',
    format: 'QA2!n4!a21!c',
    currency: 'Qatari Rial',
    currencyCode: 'QAR',
  },
  {
    country: 'Romania',
    length: '24',
    code: 'RO',
    format: 'RO2!n4!a16!c',
    currency: 'Romanian Leu',
    currencyCode: 'RON',
  },
  {
    country: 'Saint Lucia',
    length: '32',
    code: 'LC',
    format: 'LC2!n4!a24!c',
    currency: 'East Caribbean Dollar',
    currencyCode: 'XCD',
  },
  {
    country: 'San Marino',
    length: '27',
    code: 'SM',
    format: 'SM2!n1!a5!n5!n12!c',
    currency: 'Euro',
    currencyCode: 'EUR',
  },
  {
    country: 'Sao Tome And Principe',
    length: '25',
    code: 'ST',
    format: 'ST2!n8!n11!n2!n',
    currency: 'Dobra',
    currencyCode: 'STN',
  },
  {
    country: 'Saudi Arabia',
    length: '24',
    code: 'SA',
    format: 'SA2!n2!n18!c',
    currency: 'Saudi Riyal',
    currencyCode: 'SAR',
  },
  {
    country: 'Serbia',
    length: '22',
    code: 'RS',
    format: 'RS2!n3!n13!n2!n',
    currency: 'Serbian Dinar',
    currencyCode: 'RSD',
  },
  {
    country: 'Seychelles',
    length: '31',
    code: 'SC',
    format: 'SC2!n4!a2!n2!n16!n3!a',
    currency: 'Seychelles Rupee',
    currencyCode: 'SCR',
  },
  {
    country: 'Slovakia',
    length: '24',
    code: 'SK',
    format: 'SK2!n4!n6!n10!n',
    currencyCode: 'EUR',
    currency: 'Euro',
  },
  {
    country: 'Slovenia',
    length: '19',
    code: 'SI',
    format: 'SI2!n5!n8!n2!n',
    currency: 'Euro',
    currencyCode: 'EUR',
  },
  {
    country: 'Spain',
    length: '24',
    code: 'ES',
    format: 'ES2!n4!n4!n1!n1!n10!n',
    currency: 'Euro',
    currencyCode: 'EUR',
  },
  {
    country: 'Sweden',
    length: '24',
    code: 'SE',
    format: 'SE2!n3!n16!n1!n',
    currency: 'Swedish Krona',
    currencyCode: 'SEK',
  },
  {
    country: 'Switzerland',
    length: '21',
    code: 'CH',
    format: 'CH2!n5!n12!c',
    currency: 'WIR Franc',
    currencyCode: 'CHW',
  },
  {
    country: 'Timor-Leste',
    length: '23',
    code: 'TL',
    format: 'TL2!n3!n14!n2!n',
    currency: 'US Dollar',
    currencyCode: 'USD',
  },
  {
    country: 'Tunisia',
    length: '24',
    code: 'TN',
    format: 'TN2!n2!n3!n13!n2!n',
    currency: 'Tunisian Dinar',
    currencyCode: 'TND',
  },
  {
    country: 'Turkey',
    length: '26',
    code: 'TR',
    format: 'TR2!n5!n1!c16!c',
    currency: 'Turkish Lira',
    currencyCode: 'TRY',
  },
  {
    country: 'Ukraine',
    length: '29',
    code: 'UA',
    format: 'UA2!n6!n19!c',
    currency: 'Hryvnia',
    currencyCode: 'UAH',
  },
  {
    country: 'United Arab Emirates',
    length: '23',
    code: 'AE',
    format: 'AE2!n3!n16!n',
    currencyCode: 'AED',
    currency: 'UAE Dirham',
  },
];
export default countries;
