export enum ClientCategory {
  ELIGIBLE_COUNTER_PARTIES = 'ELIGIBLE_COUNTER_PARTIES',
  PROFESSIONAL_CLIENTS = 'PROFESSIONAL_CLIENTS',
  RETAIL_CUSTOMERS = 'RETAIL_CUSTOMERS',
}

export enum RiskProfile {
  CONSERVATIVE = 'CONSERVATIVE',
  MODERATE = 'MODERATE',
  BALANCED = 'BALANCED',
  DYNAMIC = 'DYNAMIC',
  AGGRESSIVE = 'AGGRESSIVE',
}
