FROM node:18

WORKDIR /usr/src/app

COPY . .

# Install dependencies using the Yarn cache from the previous build, if one exists.
RUN --mount=type=cache,target=/yarn YARN_CACHE_FOLDER=/yarn yarn install

# Build the Smart Contract API and all its local dependencies.
RUN npx nx build smart-contract-api

# Remove the Smart Contract API build files as we want NestJS to build it on startup.
RUN rm -rf ./smart-contract-api/services/smart-contract-api/dist

# Needed for using ethereum/tx on Node 18
ENV NODE_OPTIONS --openssl-legacy-provider

CMD [ "npx", "nx", "start", "smart-contract-api" ]
