export enum WalletType {
  INTERNAL_CODEFI_HASHICORP_VAULT = "INTERNAL_CODEFI_HASHICORP_VAULT",
  INTERNAL_CODEFI_AZURE_VAULT = "INTERNAL_CODEFI_AZURE_VAULT",
  INTERNAL_CODEFI_AWS_VAULT = "INTERNAL_CODEFI_AWS_VAULT",
  INTERNAL_CLIENT_AZURE_VAULT = "INTERNAL_CLIENT_AZURE_VAULT",
  INTERNAL_CLIENT_AWS_VAULT = "INTERNAL_CLIENT_AWS_VAULT",
  EXTERNAL_CLIENT_METAMASK = "EXTERNAL_CLIENT_METAMASK",
  EXTERNAL_CLIENT_METAMASK_INSTITUTIONAL = "EXTERNAL_CLIENT_METAMASK_INSTITUTIONAL",
  EXTERNAL_OTHER = "EXTERNAL_OTHER",
}
