FROM node:18

WORKDIR /usr/src/app

COPY . .

# Install dependencies using the Yarn cache from the previous build, if one exists.
RUN --mount=type=cache,target=/yarn YARN_CACHE_FOLDER=/yarn yarn install

# Build the Assets API and all its local dependencies.
RUN npx nx build assets-api

# Remove the Assets API build files as we want NestJS to build it on startup.
RUN rm -rf ./assets/services/assets-api/dist

CMD [ "npx", "nx", "start:dev", "assets-api" ]