import { ApiProperty } from "@nestjs/swagger";

export class PrivateChannelResponse {
  @ApiProperty({
    description: "Unique system generated identifier for the private channel",
  })
  id: string;

  @ApiProperty({
    description: "Name of the channel generated by the system",
  })
  channelName: string;

  @ApiProperty({
    description: "Description of the channel",
  })
  description: string;

  @ApiProperty({
    description: "Name of the Ethereum network node",
  })
  chainName: string;

  @ApiProperty({
    description: "Unique protocol generated identifier for the operation",
  })
  transactionHash: string;

  @ApiProperty({
    description: "Number of the mined ethereum block",
  })
  blockNumber: number;

  @ApiProperty({
    description:
      "List unique protocol generated identifier (public keys of Orion nodes)",
  })
  participants: string[];

  @ApiProperty({
    description: "Unique system generated identifier for the privacy group",
  })
  privacyGroup: string;
}
