import { BaseEntity } from '../data/entities/BaseEntity'

/**
 * Allows to define a new type that has all fields from type "T" autogenerated
 * fields. Useful to define "create"/"update" methods that expect a full object
 * without autogenerated fields.
 */
export type DataFieldsOnly<T> = Omit<T, keyof BaseEntity>
