version: '3.4'
services:
  i18n-api:
    env_file:
      - .env
      - ../../../.env
    environment:
      STORES_FILE: ${STORES_FILE-./config/stores.json}
    image: i18n-api
    networks:
      - codefi
    volumes:
      - ./src:/usr/src/app/assets/services/i18n-api/src:delegated
    build:
      context: ../../../
      dockerfile: ./assets/services/i18n-api/${DOCKERFILE-Dockerfile.dev}
    labels:
      local.filebeat: 'true'

networks:
  codefi:
    external:
      name: local-dev-env-deps_codefi
