FROM node:18

WORKDIR /usr/src/app

COPY . .

# Install dependencies using the Yarn cache from the previous build, if one exists.
RUN --mount=type=cache,target=/yarn YARN_CACHE_FOLDER=/yarn yarn install

# Build the i18n API and all its local dependencies.
RUN npx nx build i18n-api

# Remove the i18n API build files as we want NestJS to build it on startup.
RUN rm -rf ./assets/services/i18n-api/dist

CMD [ "npx", "nx", "start:dev", "i18n-api" ]
